name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: slive-svelte:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }}
            TWITCH_REDIRECT_URI=${{ secrets.TWITCH_REDIRECT_URI }}

      - name: Test the image
        run: |
          docker run --rm \
            -e TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }} \
            -e TWITCH_REDIRECT_URI=${{ secrets.TWITCH_REDIRECT_URI }} \
            slive-svelte:latest node -e 'console.log("Node.js version:", process.version)'
